config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'pages/home'
  resources :games do
    post :check, on: :member
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  before_action :set_game, only: %i[show edit update destroy check]

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show
    word_length = @game.word.length
    @word_array = @game.word.split('')
    @hidden_word = Array.new(word_length, '*').join('')
  end

  # GET /games/new
  def new
    @auto_game = true if params[:auto] == 'true'
    @game = Game.new
  end

  # GET /games/1/edit
  def edit; end

  def check
    @word = @game.word
    @used_letters = session[:used_letters] || []
    letter = params[:letter]
    word_length = @game.word.length
    @word_array = @game.word.split('')

    # Retrieve @hidden_word_array from session if it exists, otherwise initialize a new one
    @hidden_word_array = session[:hidden_word_array] || Array.new(word_length, '*')
    @hidden_word = @hidden_word_array.join('')

    if @word_array.include?(letter)
      @word_array.each_index do |index|
        if @word_array[index] == letter
          @hidden_word_array[index] = letter
        end
      end

      @hidden_word = @hidden_word_array.join('')
      # Store @hidden_word_array in session
      session[:hidden_word_array] = @hidden_word_array
      @finished_game = finished_game?
    else
      @used_letters << letter unless @used_letters.include?(letter)
      session[:used_letters] = @used_letters
      @used_letters = @used_letters.join(',')

      respond_to do |format|
        format.html { redirect_to game_path } # Redirect if needed
        format.turbo_stream do
          render turbo_stream: turbo_stream.update('used_letters', partial: 'used_letters',
                                                   locals: { used_letters: @used_letters })
        end
      end
    end
  end

  # POST /games or /games.json
  def create
    if params[:game][:auto_game] == 'true'
      random_word = Word.all.sample.name.downcase
      @game = Game.new(word: random_word)
    else
      @game = Game.new(game_params)
    end


    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy
    session.delete(:hidden_word_array)
    session.delete(:used_letters)

    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(:word)
  end

  def finished_game?
    @word == @hidden_word
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/games_helper.rb
# frozen_string_literal: true

module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/games/_finished_game.html.erb
<h3>You've guessed it! Well done!</h3>

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :word, class: 'block text-sm font-medium text-gray-700 text-xl', value: @auto_game unless
          @auto_game %>
    <%= form.text_field :word, class: 'w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500
                                       focus:ring-indigo-500 sm:text-sm max-w-max mt-0' unless auto_game %>
    <%# this field below is needed to get auto_game flag available in create action %>
    <%= form.hidden_field :auto_game, value: @auto_game if auto_game %>
    <%= form.button class: "p-3 rounded-lg text-white bg-teal-500 mb-5 mt-5" %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <p class="text-2xl">Word: <%= game.word.capitalize %></p>
</div>

app/views/games/_hidden_word.html.erb
<h1 class="text-3xl tracking-wide"><%= hidden_word.capitalize %></h1>

app/views/games/_used_letters.html.erb
<h1><%= used_letters %></h1>

app/views/games/check.turbo_stream.erb
<%= turbo_stream.update 'hidden_word' do %>
  <%= render 'hidden_word', hidden_word: @hidden_word %>
<% end %>

<%= turbo_stream.append 'hidden_word' do %>
  <%= render 'finished_game' if @finished_game %>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-4xl mb-5">Games</h1>

<div id="games">
  <% @games.each do |game| %>
    <%= render game %>
    <p class="mt-5 mb-8">
      <%= link_to "Play this game", game, class: 'p-3 rounded-lg text-white bg-orange-500' %>
    </p>
  <% end %>
</div>

<%= link_to "New game", new_game_path, class: 'p-3 bg-sky-500 rounded-lg text-white' %>
<%= link_to "Create game with random word", new_game_path(auto: true), class: 'p-3 bg-yellow-500 text-white
                                                                              rounded-lg' %>

app/views/games/new.html.erb
<%= content_tag(:h1, "Create new game", class: "text-4xl") unless @auto_game %>
<%= content_tag(:h1, "Create new game with random word", class: "text-4xl") if @auto_game %>

<%= render "form", game: @game, auto_game: @auto_game %>
<%= link_to "Back to games", games_path, class: 'p-3 text-white bg-purple-600 rounded-lg' %>

app/views/games/show.html.erb
<p style="color: green"><%= notice %></p>
<h1 class="text-4xl">Guess the word!</h1>


<%= turbo_stream_from 'hidden_word' %>
<%= turbo_stream_from 'used_letters' %>

<div id='hidden_word'>
  <h1 class="text-3xl"><%= @hidden_word.capitalize %></h1>
</div>

<%= form_with url: check_game_path(@game), method: :post do |form| %>
  <%= form.text_field :letter, placeholder: 'Enter your letter', class: 'block w-full rounded-md border-gray-300
      shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm inline-block max-w-max' %>
  <%= form.button 'Submit', class: "p-3 rounded-lg text-white bg-sky-500 mb-5" %>
<% end %>


<div>
  <h3 class="text-3xl">Already used letters</h3>
  <p id='used_letters' class="text-2xl mb-5"><%= @used_letters %></p>
</div>

<div>
  <%= link_to "Edit this game", edit_game_path(@game), class: 'p-3 rounded-lg text-white bg-orange-500' %>
  <%= link_to "Back to games", games_path, class: 'p-3 rounded-lg text-white bg-purple-600' %>

  <%= button_to "Destroy this game", @game, method: :delete, class: 'p-3 rounded-lg text-white bg-red-500 mt-5' %>
</div>

app/views/layouts/_navbar.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<nav class="bg-gray-800">
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="flex h-16 items-center justify-between">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <img class="hidden h-8 w-auto lg:block" src="" alt="Your Company">
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <%= link_to "Home", root_path, class: "rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white" %>
            <%= link_to "Games", games_path, class: "rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white" %>
          </div>
        </div>
      </div>
      <div class="-mr-2 flex sm:hidden">
        <button type="button" class="inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Capybara</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('capybara.png') %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="bg-cover bg-center" style="background-image: url('<%= asset_path('galaxy.jpg') %>')">
  <div class="pt-40 pl-36 text-white">
    <%= link_to new_game_path do %>
      <div class="p-5 border border-gray-900 rounded-full text-black inline-block max-w-max">
        New capybara game. Learn more about it!
      </div>
    <% end %>
    <h1 class="font-semibold italic text-5xl mt-4">A fun capybara game to enjoy and </h1>
    <h1 class="font-semibold italic text-5xl mt-4">boost children to learn new words</h1>
  </div>
</div>